const listings = [
    {
      title: "Cozy Apartment",
      description: "A beautiful apartment in the city center.",
      image: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
      price: 1200,
      location: "Gwalior",
      country: "INDIA",
    },
    {
      title: "Modern Villa",
      description: "Luxury villa with ocean view.",
      image: "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg",
      price: 5000,
      location: "Los Angeles",
      country: "USA",
    },
    {
      title: "Small Studio",
      description: "Compact and affordable living space.",
      image: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg",
      price: 800,
      location: "San Francisco",
      country: "USA",
    },
    {
      title: "Beach House",
      description: "Stay by the beach and enjoy the waves.",
      image: "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg",
      price: 2500,
      location: "Miami",
      country: "USA",
    },
    {
      title: "Mountain Cabin",
      description: "Peaceful retreat in the mountains.",
      image: "https://images.pexels.com/photos/2383854/pexels-photo-2383854.jpeg",
      price: 1500,
      location: "Denver",
      country: "USA",
    },
    {
      title: "Penthouse Suite",
      description: "High-rise penthouse with skyline views.",
      image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
      price: 7000,
      location: "Chicago",
      country: "USA",
    },
    {
      title: "Countryside Home",
      description: "A perfect getaway from the city noise.",
      image: "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg",
      price: 1000,
      location: "Texas",
      country: "USA",
    },
    {
      title: "Luxury Condo",
      description: "Modern condo in a prime location.",
      image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg",
      price: 4000,
      location: "Seattle",
      country: "USA",
    },
    {
      title: "Suburban House",
      description: "Spacious house in a quiet neighborhood.",
      image: "https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg",
      price: 2000,
      location: "Atlanta",
      country: "USA",
    },
    {
      title: "Farmhouse",
      description: "Traditional farmhouse with a large backyard.",
      image: "https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg",
      price: 1800,
      location: "Kansas",
      country: "USA",
    },
    {
      title: "Lakeview Cabin",
      description: "Stunning views of the lake from your window.",
      image: "https://images.pexels.com/photos/1486785/pexels-photo-1486785.jpeg",
      price: 2200,
      location: "Minnesota",
      country: "USA",
    },
    {
      title: "Urban Loft",
      description: "Stylish loft in the heart of the city.",
      image: "https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg",
      price: 3500,
      location: "Boston",
      country: "USA",
    },
    {
      title: "Desert House",
      description: "Enjoy the tranquility of the desert.",
      image: "https://images.pexels.com/photos/259846/pexels-photo-259846.jpeg",
      price: 2700,
      location: "Arizona",
      country: "USA",
    },
    {
      title: "Cottage",
      description: "Charming cottage surrounded by nature.",
      image: "https://images.pexels.com/photos/302321/pexels-photo-302321.jpeg",
      price: 1600,
      location: "Vermont",
      country: "USA",
    },
    {
      title: "Ski Lodge",
      description: "Perfect stay for ski enthusiasts.",
      image: "https://images.pexels.com/photos/326647/pexels-photo-326647.jpeg",
      price: 3000,
      location: "Colorado",
      country: "USA",
    },
  ];
  

  module.exports = {data : listings};